name: recycle
description: 2020 CapstoneDesign TeamProject Team No.5

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #푸시 알람
  firebase_messaging: ^6.0.16

  #광고 삽입을 위한 패키지
  firebase_core: ^0.4.5
  firebase_admob: ^0.9.3+2

  # 이메일 인증 코드를 발급하기 위한 random code generator library
  random_string: ^2.0.1

  # 페이지 전환 효과 라이브러리
  page_transition: ^1.1.5

  # 캘린더
  flutter_calendar_carousel: ^1.4.12

  # http 통신에 필요한 라이브러리
  http: ^0.12.1

  # mailer SMTP
  mailer: ^3.0.4

  # for Bottom alert feature...
  fluttertoast: ^4.0.1

  #이메일 전송 라이브러리2 -> 이건 진짜 된다.
  url_launcher: ^5.4.7

  # 도로명주소 API
  kopo: ^0.1.1

  # 카메라 모듈을 불러오기 위함.
  image_picker: ^0.6.5+3

  # cloud firestore
  cloud_firestore: ^0.13.5

  # firebase storage :: 이미지
  firebase_storage: ^3.1.5

  # Image.network()는 페이지 전환할 때 마다 이미지를 다시 불러와 비효율적이다. 캐시로 저장하고 있으면 좋다.
  cached_network_image: ^2.1.0+1

  #  파일 읽고 쓰는 라이브러리.
  path_provider: ^1.6.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/icon/Trash_bin.png
    - assets/json/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages